### ISSUE TITLE
格式化CMakeLists.txt的时候，会自动把#注释内容删掉

### ISSUE THREAD

**Issue by whiskey-ibuprofen** [quanzhuo/cmake-intellisence#1]

**Comment by quanzhuo** [comment]
@whiskey-ibuprofen 感谢反馈，但是我这边没法复现。
你可以试试最新版本的 插件 0.2.1, 看看还有这个问题吗？
如果最新版本的插件还有这个问题，请把 CMakeLists.txt 文件的内容 发出来。

**Comment by whiskey-ibuprofen** [comment]
我另外一个电脑试了下也没有问题，可能是我那台电脑的配置问题。请问下设置cmake的默认格式化工具是我们这个插件的话，是不是有什么配置来着

**Comment by quanzhuo** [comment]
> 我另外一个电脑试了下也没有问题，可能是我那台电脑的配置问题。请问下设置cmake的默认格式化工具是我们这个插件的话，是不是有什么配置来着

如果你只安装了 cmake-intellisence 插件，那么直接按下 shift+ Alt + F （Windows 快捷键）就会自动使用该插件格式化，如果你安装了多个具有 cmake 格式化功能的插件的话，当你按下  shift+ Alt + F  时，会弹出如下对话框：
![image](https://github.com/user-attachments/assets/5d0ce31b-12f6-428e-9f3a-9a66f34ae5c4)
点击 配置，在弹出的 quick pick 中选择 CMake Intellisence 即可：
![image](https://github.com/user-attachments/assets/4f1f0fc0-d9c6-4119-8b63-b995068f0940)

**Comment by whiskey-ibuprofen** [comment]
![image](https://github.com/user-attachments/assets/03b7346c-96d7-436c-bbda-4a6a4a7869cf)
请问下这个是因为哪个没配置？

**Comment by whiskey-ibuprofen** [comment]
是不是cmaketools里面的"cmake.sourceDirectory"这个没设置，就会出现这个问题？

**Comment by whiskey-ibuprofen** [comment]
我测试是正确设置这个选项之后，就不会出现了。麻烦帮忙看下~~~~~~~

**Comment by whiskey-ibuprofen** [comment]
另外，能否介绍下这几个cmake插件之间的依赖关系

**Comment by quanzhuo** [comment]
> 另外，能否介绍下这几个cmake插件之间的依赖关系
> 

CMake Intellisence 插件对CMake 语言提供自动补全，语义高亮，文档链接，格式化等lsp 编辑特性。另外还有两个类似的插件,名字分别叫做 CMake 和 CMake Language Support。这三个插件都是CMake 语言支持插件，只是支持的功能不一，依赖不一。CMake IntelliSence 插件不依赖与任何其他插件，它只依赖于系统中的CMake 可执行程序。CMake Language Support 依赖于.net。

 CMake Tools 插件是一个CMake 工作流插件，它和另外三个插件的功能没有交集，主要用于 CMake 项目的配置和构建。

**Comment by whiskey-ibuprofen** [comment]
现在新版本发现，()不在同一行的时候，执行格式化，)会自动格式化到行首，上个版本不会的。请问您那里出现了吗

**Comment by quanzhuo** [comment]
> 现在新版本发现，()不在同一行的时候，执行格式化，)会自动格式化到行首，上个版本不会的。请问您那里出现了吗

应该是 bug。我会尽快修复

**Comment by whiskey-ibuprofen** [comment]
厉害的老哥
